yolo_model:

  config_file:
    name: yolov3-custom.cfg
  weight_file:
    name: yolov3-custom_last.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - up
      - down
      - run
      - emergency
      - cam_switch
      - selector

